### ISSUE TITLE
Feature request:  Allow multiple .inf files in source directory

### ISSUE THREAD

**Issue by TechCowboy** [ByteProject/Puny-BuildTools#13]
Small change to the puny script to allow user to make his adventure more modular by including other .inf files in his main source.  These additional files would exist in the same directory.

Simply add ```++./``` inside the puny script.

See below.
```
main()
{
	$inform -d2esi $v +$lib ++./ $game
	game=`basename $game .inf`
	printf "\n"
	exit 0
}
```

Example:
Assuming main.inf is the adventure, within that file, he could include additional files which are located in his source directory. 

```
! <normal puny stuff>
! end main.inf file

Include "apartment.inf";
Include "buildings.inf";
Include "mayor.inf";
Include "streets.inf";
```

**Comment by ByteProject** [comment]
Thanks for your suggestion. I think that's not the right way to do it. This would add any .inf file in the project directory to the compilation process, which may not be what the author wants. What if you are maintaining two versions of a game in the same project dir, e.g. **zork.inf** and **minizork.inf**.

Instead, just do it the way the Inform Designer's Manual suggest for adding additional source files residing in the same dir as the main file (with the > syntax).

```
Include "globals.h";

! import external code for this story 
Include ">abbrvs.h";
Include ">punyhacks.h";
```

**Comment by TechCowboy** [comment]
I'm such a noob at this.  Missed this in the documentation.
