### ISSUE TITLE
Error compiling default shell.inf

### ISSUE THREAD

**Issue by hsicilia** [ByteProject/Puny-BuildTools#4]
When I compile the default shell.inf file or run any of the commands to generate an image (for example speccy.sh) always returns me this error:

```
line 967: Error: Two different verb definitions refer to "feel"
> Verb 'feel' = 'touch';
```

If I comment this line the error disappears and I can generate the disk images without any problem.

I've posted this on [Intficion forum](https://intfiction.org/t/puddle-buildtools-for-punyinform-releases/51322/34?u=lenko), too.

**Comment by ByteProject** [comment]
This was due to a change in PunyInform. Comment if you run into this error, comment the line as seen above.
