### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by markusbkk** [ByteProject/Puny-BuildTools#7]
Just curious. Is there any way to add more graphics than the splash screen?
I know emulating the way DAAD or Magnetic handle graphics would be difficult and require support within all the interpreters.
I'm thinking maybe there is at least a way to interrupt gameplay and display a fullscreen image?

I'm mainly interested in doing this on C64, Amiga and Amstrad CPC.

**Comment by ByteProject** [comment]
The Z-machine is unfortunately not designed to handle graphics on these machines. I am sure there is way to achieve what you are after but this would be hacking and not in the way the designers of the Z-machine intended the games to be played. Supporting this would be beyond the scope of the BuildTools, I am sorry. On C64, Frodewin did something that goes in your direction but it was done with much knowledge of the machine, much more than I have. You can have a look at the game here https://comsha.itch.io/dragon-princess. If you want to learn more about it, he is regularly on the PunyInform Discord server and probably can help you. I am pretty sure what he did is not easily applicable to Amiga and CPC. DAAD is definitely the more suitable system to what you aim for. I am closing this issue now.
